### ISSUE TITLE
Area Handler continuing?

### ISSUE THREAD

**Issue by Qwertyus3D** [antilectual/IC_Addons#1]
Hi, could you make a version of Area Handler addon https://github.com/mikebaldi/IC_Addons/tree/main/IC_AreaHandler , compatible with current version of ScriptHub? Mike doesn't want to maintain it, while the addon is quite useful. But it can't work with new script after latest additions, showing a critical error and exiting.

**Comment by antilectual** [comment]
I admittedly missed that addon when I was updating Script Hub since I didn't have it installed. However, I'm sorry, but since it contains memory writing I do not intend to write an update to it.

You may try reverting Script Hub to the [version](https://github.com/mikebaldi/Idle-Champions/releases/tag/Stable_v500) before its refactor to see if the addon continues to work, but without anyone maintaining the addon, it looks as though the it will eventually stop working when the custom offsets it is using change.
